Repository oodd-team/oodd-web-react, pull requests merged in 2024-12, with the labels that each got.

#89 [OD-135] Chats 페이지 정비
  .github/workflows/dev_cicd.yml
  .github/workflows/prod_cicd.yml
  src/apis/chatting/dto.ts
  src/pages/Chats/ChatRoom/ChatBox/index.tsx
  src/pages/Chats/ChatRoom/createExtendedMessages.ts
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Chats/ChatRoomItem/index.tsx
  src/pages/Chats/Request/Cards/Card/index.tsx
  src/pages/Chats/Request/Cards/Card/styles.tsx
  src/pages/Chats/Request/Cards/styles.tsx
  src/pages/Chats/TabBar/index.tsx
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/index.tsx
  src/pages/ProfileViewer/UserInfo/index.tsx
Labels: refactor, chore

#90 [OD-136] 리다이렉트 URL에 환경 변수 추가
  src/pages/Login/components/Kakao/index.tsx
  src/pages/Login/components/Naver/index.tsx
  src/pages/ProfileViewer/UserInfo/index.tsx
Labels: fix

#91 [OD-135] workflow env 설정 코드 수정
  .github/workflows/dev_cicd.yml
  .github/workflows/prod_cicd.yml
Labels: fix

#94 [OD-135] dev/prod 환경에 따라 workflow api url 분리
  .github/workflows/dev_cicd.yml
  .github/workflows/prod_cicd.yml
Labels: fix

#98 [OD-161] cicd workflow 수정
  .github/workflows/CD_dev.yml
  .github/workflows/CD_prod.yml
  .github/workflows/CI_dev.yml
  .github/workflows/CI_prod.yml
Labels: fix

#99 CI/CD workflow 수정
  .github/workflows/CD_dev.yml
  .github/workflows/CD_prod.yml
  .github/workflows/CI_dev.yml
  .github/workflows/CI_prod.yml
Labels: fix

#100 [OD-157] myPage & profileViewer 조건부렌더링으로 수정
  src/App.tsx
  src/components/NavBar/index.tsx
  src/components/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/components/PostBase/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPost/index.tsx
  src/pages/PostImageSelect/index.tsx
  src/pages/PostInstaFeedSelect/index.tsx
  src/pages/PostUpload/index.tsx
  src/pages/Profile/ButtonSecondary/index.tsx
  src/pages/Profile/ButtonSecondary/styles.tsx
  src/pages/Profile/NavbarProfile/index.tsx
  src/pages/Profile/NavbarProfile/styles.tsx
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
  src/pages/ProfileEdit/index.tsx
  src/pages/ProfileViewer/UserInfo/index.tsx
  src/pages/ProfileViewer/UserInfo/styles.tsx
  src/pages/ProfileViewer/index.tsx
  src/pages/ProfileViewer/style.tsx
Labels: fix, refactor

#101 [OD-161] 불필요한 의존성 정리
  package.json
  src/apis/core/index.ts
  src/config/constant.ts
  src/pages/PostUpload/index.tsx
  tsconfig.app.json
  yarn.lock
Labels: fix, chore

#102 [OD-163] Home 리팩토링
  src/pages/Home/HomeTopBar/index.tsx
  src/pages/Home/HomeTopBar/styles.tsx
  src/pages/Home/OOTD/Feed/dto.ts
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/dto.ts
  src/pages/Home/OOTD/index.tsx
  src/pages/Home/dto.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.tsx
  tsconfig.app.json
  vite.config.ts
Labels: feat, refactor

#106 [OD-153] recoil 폴더 내 import문 정리
  src/apis/chat-room/dto.ts
  src/recoil/Chats/AllMessages.ts
  src/recoil/Post/PostAtom.ts
  src/recoil/Post/PostCommentAtom.ts
  src/recoil/PostUpload/PostUploadAtom.ts
  src/recoil/ProfileViewer/userDetailsAtom.ts
  src/recoil/util/OpponentInfo.ts
Labels: refactor

#104 [OD-146] Login 페이지 변수명명 규칙 점검 및 코드 순서 정리
  src/App.tsx
  src/pages/Login/LoginComplete/index.tsx
  src/pages/Login/SocialLoginButton/dto.ts
  src/pages/Login/SocialLoginButton/index.tsx
  src/pages/Login/SocialLoginButton/style.tsx
  src/pages/Login/components/Kakao/index.tsx
  src/pages/Login/components/Naver/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/styles.tsx
  src/utils/getCurrentUserId.ts
Labels: refactor

#105 [OD-149] 회원가입 페이지 & 이용약관 동의 페이지 변수 명명 규칙 점검 및 코드 순서 정리
  src/apis/user/index.ts
  src/components/TopBar/styles.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.tsx
  src/pages/TermsAgreement/index.tsx
  src/pages/TermsAgreement/styles.tsx
Labels: refactor

#103 [OD-140] svg 파일 컴포넌트화
  src/assets/arrow/bottom.svg
  src/assets/default/insta.svg
  src/assets/default/like-white.svg
  src/assets/default/oodd-white.svg
  src/assets/default/photo.svg
  src/components/Icons/Alarm.tsx
  src/components/Icons/Heart.tsx
  src/components/Icons/Home.tsx
  src/components/Icons/Like.tsx
  src/components/Icons/Message.tsx
  src/components/Icons/MyPage.tsx
  src/components/Icons/Photo.tsx
  src/components/Icons/dto.ts
Labels: refactor

#107 [OD-142] Chats 리팩토링
  src/pages/Chats/ChatRoom/ChatBox/index.tsx
  src/pages/Chats/ChatRoom/ChatBox/styles.tsx
  src/pages/Chats/ChatRoom/DateBar/index.tsx
  src/pages/Chats/ChatRoom/DateBar/styles.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/index.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/styles.tsx
  src/pages/Chats/ChatRoom/SentMessage/index.tsx
  src/pages/Chats/ChatRoom/SentMessage/styles.tsx
  src/pages/Chats/ChatRoom/createExtendedMessages.ts
  src/pages/Chats/ChatRoom/dto.ts
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Chats/ChatRoomItem/index.tsx
  src/pages/Chats/ChatRoomItem/styles.tsx
  src/pages/Chats/Matching/Cards/Card/dto.ts
  src/pages/Chats/Matching/Cards/Card/index.tsx
  src/pages/Chats/Matching/Cards/Card/styles.tsx
  src/pages/Chats/Matching/Cards/dto.ts
  src/pages/Chats/Matching/Cards/index.tsx
  src/pages/Chats/Matching/Cards/styles.tsx
  src/pages/Chats/Matching/dto.ts
  src/pages/Chats/Matching/index.tsx
  src/pages/Chats/Matching/styles.tsx
  src/pages/Chats/RecentChat/index.tsx
  src/pages/Chats/RecentChat/styles.tsx
  src/pages/Chats/TabBar/index.tsx
  src/pages/Chats/dto.ts
  src/pages/Chats/index.tsx
  src/pages/Chats/styles.tsx
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/Feed/styles.tsx
  src/pages/SignUp/index.tsx
  src/pages/TermsAgreement/index.tsx
  tsconfig.app.json
  vite.config.ts
Labels: feat, refactor

#110 [OD-151] Home 무한 스크롤 수정
  package.json
  src/pages/Home/HomeTopBar/index.tsx
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/index.tsx
  yarn.lock
Labels: refactor

#111 [OD-165] 공통 컴포넌트 (TopBar, UserProfile, PostItem) 리팩토링
  src/App.tsx
  src/components/PostItem/dto.ts
  src/components/PostItem/index.tsx
  src/components/PostItem/style.tsx
  src/components/TopBar/dto.ts
  src/components/TopBar/index.tsx
  src/components/TopBar/styles.tsx
  src/components/UserProfile/dto.ts
  src/components/UserProfile/index.tsx
  src/components/UserProfile/style.tsx
  src/pages/AccountCancel/index.tsx
  src/pages/AccountEdit/index.tsx
  src/pages/AccountSetting/index.tsx
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Home/HomeTopBar/index.tsx
  src/pages/Home/OOTD/Feed/dto.ts
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Login/LoginComplete/index.tsx
  src/pages/Login/SocialLoginButton/index.tsx
  src/pages/Login/SocialLoginButton/style.tsx
  src/pages/Login/index.tsx
  src/pages/Login/styles.tsx
  src/pages/PostImageSelect/index.tsx
  src/pages/PostInstaFeedSelect/index.tsx
  src/pages/PostUpload/index.tsx
  src/pages/Profile/index.tsx
  src/pages/ProfileEdit/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.tsx
  src/pages/TermsAgreement/index.tsx
  src/pages/TermsAgreement/styles.tsx
  src/pages/verification/index.tsx
  tsconfig.app.json
  vite.config.ts
Labels: refactor

#112 [OD-166] 공통 컴포넌트 리팩토링
  src/components/BottomSheet/OptionsBottomSheet/ReportBottomSheetMenu/index.tsx
  src/components/BottomSheet/OptionsBottomSheet/dto.ts
  src/components/BottomSheet/OptionsBottomSheet/index.tsx
  src/components/BottomSheet/OptionsBottomSheet/styles.tsx
  src/components/BottomSheet/dto.ts
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/styles.tsx
  src/components/BottomSheetMenu/dto.ts
  src/components/BottomSheetMenu/index.tsx
  src/components/BottomSheetMenu/styles.tsx
  src/components/CommentBottomSheet/Comment/dto.ts
  src/components/CommentBottomSheet/Comment/index.tsx
  src/components/CommentBottomSheet/Comment/styles.tsx
  src/components/CommentBottomSheet/dto.ts
  src/components/CommentBottomSheet/index.tsx
  src/components/CommentBottomSheet/styles.tsx
  src/components/Frame/Frame.tsx
  src/components/Icons/Alarm.tsx
  src/components/Icons/Heart.tsx
  src/components/Icons/Home.tsx
  src/components/Icons/Like.tsx
  src/components/Icons/Message.tsx
  src/components/Icons/MyPage.tsx
  src/components/Loading/styles.tsx
  src/components/Modal/index.tsx
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.tsx
  src/components/Text/StyledText.tsx
  src/components/Text/dto.ts
  src/pages/Chats/ChatRoom/index.tsx
Labels: refactor

#114 [OD-156] user-block, user-report 도메인 request 수정
  src/apis/user-block/dto.ts
  src/apis/user-block/index.ts
  src/apis/user-report/dto.ts
  src/apis/user-report/index.ts
  src/components/BottomSheet/OptionsBottomSheet/index.tsx
  src/components/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Home/OOTD/Feed/index.tsx
Labels: refactor

#113 [OD-154] user, auth 도메인 response 응답에 따라 dto 수정
  src/apis/auth/dto.ts
  src/apis/auth/index.ts
  src/apis/user-block/index.ts
  src/apis/user-report/index.ts
  src/apis/user/dto.ts
  src/apis/user/index.ts
  src/pages/Login/LoginComplete/index.tsx
  src/recoil/ProfileViewer/userDetailsAtom.ts
Labels: refactor

#109 [OD-158] 컬러시스템 구축 & Post, MyPost 합치기
  src/App.tsx
  src/assets/default/delete.svg
  src/assets/default/edit.svg
  src/assets/default/pin.svg
  src/components/BottomButton/styles.tsx
  src/components/ClothingInfoItem/styles.tsx
  src/components/Modal/styles.tsx
  src/components/PostItem/style.tsx
  src/pages/AccountCancel/index.tsx
  src/pages/AccountCancel/styles.tsx
  src/pages/MyPost/index.tsx
  src/pages/MyPost/styles.tsx
  src/pages/Post/PostBase/ImageSwiper/index.tsx
  src/pages/Post/PostBase/ImageSwiper/styles.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/CommentItem/dto.ts
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/CommentItem/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/CommentItem/styles.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/MenuButtonList/dto.ts
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/MenuButtonList/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/MenuButtonList/styles.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/styles.tsx
  src/pages/Post/PostBase/dto.ts
  src/pages/Post/PostBase/index.tsx
  src/pages/Post/PostBase/styles.tsx
  src/pages/Post/index.tsx
  src/pages/PostUpload/SearchBottomSheetContent/index.tsx
  src/pages/PostUpload/SearchBottomSheetContent/styles.tsx
  src/pages/PostUpload/index.tsx
  src/pages/PostUpload/styles.tsx
  src/pages/Profile/ButtonSecondary/index.tsx
  src/pages/Profile/ButtonSecondary/styles.tsx
  src/pages/Profile/NavbarProfile/styles.tsx
  src/pages/Profile/index.tsx
  src/styles/theme.ts
  tsconfig.app.json
Labels: refactor

#115 [OD-152] matching & chatting 도메인 api 응답 수정
  src/apis/chatting/dto.ts
  src/apis/matching/dto.ts
  src/apis/matching/index.ts
  src/components/CommentBottomSheet/Comment/index.tsx
  src/pages/Chats/ChatRoom/ChatBox/index.tsx
  src/pages/Chats/ChatRoom/createExtendedMessages.ts
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Chats/ChatRoomItem/index.tsx
  src/pages/Chats/Matching/Cards/Card/index.tsx
  src/pages/Chats/Matching/Cards/index.tsx
  src/pages/Chats/RecentChat/index.tsx
  src/pages/Chats/TabBar/index.tsx
  src/recoil/util/OtherUser.ts
Labels: fix, refactor

#117 [OD-167] Chats/Home/컴포넌트 컬러시스템 적용
  src/components/BottomSheet/OptionsBottomSheet/ReportBottomSheetMenu/styles.tsx
  src/components/BottomSheet/OptionsBottomSheet/index.tsx
  src/components/BottomSheet/OptionsBottomSheet/styles.tsx
  src/components/BottomSheet/styles.tsx
  src/components/BottomSheetMenu/index.tsx
  src/components/BottomSheetMenu/styles.tsx
  src/components/CommentBottomSheet/Comment/styles.tsx
  src/components/CommentBottomSheet/index.tsx
  src/components/CommentBottomSheet/styles.tsx
  src/components/Frame/Frame.tsx
  src/components/Loading/styles.tsx
  src/components/Modal/styles.tsx
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.tsx
  src/components/Text/StyledText.tsx
  src/pages/Chats/ChatRoom/ChatBox/index.tsx
  src/pages/Chats/ChatRoom/ChatBox/styles.tsx
  src/pages/Chats/ChatRoom/DateBar/index.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/index.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/styles.tsx
  src/pages/Chats/ChatRoom/SentMessage/index.tsx
  src/pages/Chats/ChatRoom/SentMessage/styles.tsx
  src/pages/Chats/ChatRoom/createExtendedMessages.ts
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Chats/ChatRoomItem/index.tsx
  src/pages/Chats/Matching/Cards/Card/index.tsx
  src/pages/Chats/Matching/Cards/Card/styles.tsx
  src/pages/Chats/Matching/index.tsx
  src/pages/Chats/RecentChat/index.tsx
  src/pages/Chats/TabBar/index.tsx
  src/pages/Chats/TabBar/styles.tsx
  src/pages/Chats/index.tsx
  src/pages/Home/HomeTopBar/styles.tsx
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/Feed/styles.tsx
  src/pages/Home/OOTD/index.tsx
  src/pages/Home/OOTD/styles.tsx
  src/pages/Home/styles.tsx
Labels: refactor

#116 [OD-150] profile, profileEdit, accountEdit, accountCancel, accountSetting, verification 기존 폰트 및 색상 삭제 후 수정
  src/components/BottomButton/index.tsx
  src/components/BottomButton/styles.tsx
  src/pages/AccountCancel/index.tsx
  src/pages/AccountCancel/styles.tsx
  src/pages/AccountEdit/index.tsx
  src/pages/AccountEdit/styles.tsx
  src/pages/AccountSetting/index.tsx
  src/pages/AccountSetting/styles.tsx
  src/pages/Profile/ButtonSecondary/index.tsx
  src/pages/Profile/ButtonSecondary/styles.tsx
  src/pages/Profile/NavbarProfile/index.tsx
  src/pages/Profile/NavbarProfile/styles.tsx
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
  src/pages/ProfileEdit/index.tsx
  src/pages/ProfileEdit/styles.tsx
  src/pages/verification/index.tsx
  src/pages/verification/styles.tsx
Labels: fix, refactor

#119 [OD-148] post 도메인 응답 dto 수정
  src/apis/post/dto.ts
  src/apis/util/dto.ts
  src/components/PostItem/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/pages/Post/PostBase/index.tsx
  src/pages/PostImageSelect/index.tsx
  src/pages/PostInstaFeedSelect/index.tsx
  src/pages/PostUpload/index.tsx
Labels: refactor

#120 [OD-171] Login, SignUp, TermsAgreement 페이지와 담당 공통 컴포넌트에 컬러시스템 적용
  src/components/PostItem/index.tsx
  src/components/PostItem/style.tsx
  src/components/TopBar/index.tsx
  src/components/TopBar/styles.tsx
  src/components/UserProfile/index.tsx
  src/pages/Login/SocialLoginButton/index.tsx
  src/pages/Login/SocialLoginButton/style.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/style.tsx
  src/pages/TermsAgreement/styles.tsx
Labels: refactor

#121 [OD-168] Post 페이지 리팩토링
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/CommentItem/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/MenuButtonList/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/pages/Post/PostBase/index.tsx
  src/pages/Post/index.tsx
Labels: refactor
