Repository oodd-team/oodd-web-react, pull requests merged in 2025-03, with the labels that each got.

#136 [OD-197] UI 점검 및 자잘한 수정
  src/pages/Account/AccountCancel/styles.tsx
  src/pages/Account/AccountEdit/styles.tsx
  src/pages/Account/AccountSetting/styles.tsx
  src/pages/Profile/ButtonSecondary/styles.tsx
  src/pages/Profile/NavbarProfile/styles.tsx
  src/pages/Profile/ProfileEdit/styles.tsx
  src/pages/Profile/UserProfile/style.tsx
  src/pages/Profile/styles.tsx
Labels: fix, refactor

#138 [OD-207] 인증 정보 검사 로직 수정
  src/App.tsx
Labels: fix

#140 [OD-201] 스켈레톤 UI 컴포넌트화 및 Profile/Account/Post 적용
  src/components/Skeleton/index.tsx
  src/components/Skeleton/styles.tsx
  src/pages/Account/AccountCancel/index.tsx
  src/pages/Account/AccountSetting/index.tsx
  src/pages/Account/AccountSetting/styles.tsx
  src/pages/Post/index.tsx
  src/pages/Post/styles.tsx
  src/pages/Profile/ButtonSecondary/styles.tsx
  src/pages/Profile/ProfileEdit/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
Labels: feat, refactor
