Repository oodd-team/oodd-web-react, pull requests merged in 2025-01, with the labels that each got.

#124 [OD-173] profile, profileEdit, accountCancel, accountSetting getCurrentUserId로 수정
  src/pages/Account/AccountCancel/index.tsx
  src/pages/Account/AccountEdit/index.tsx
  src/pages/Account/AccountEdit/styles.tsx
  src/pages/Account/AccountSetting/index.tsx
  src/pages/Account/Verification/index.tsx
  src/pages/Profile/ProfileEdit/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
Labels: fix, refactor

#125 [OD-169] PostImageSelect, PostUpload 리팩토링
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.tsx
  src/pages/Post/PostBase/ImageSwiper/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/CommentItem/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/MenuButtonList/styles.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/styles.tsx
  src/pages/Post/PostBase/index.tsx
  src/pages/Post/PostBase/styles.tsx
  src/pages/Post/PostImageSelect/ImageSwiper/index.tsx
  src/pages/Post/PostImageSelect/index.tsx
  src/pages/Post/PostImageSelect/styles.tsx
  src/pages/Post/PostInstaConnect/index.tsx
  src/pages/Post/PostInstaConnect/styles.tsx
  src/pages/Post/PostUpload/ImageSwiper/index.tsx
  src/pages/Post/PostUpload/ImageSwiper/styles.tsx
  src/pages/Post/PostUpload/SearchBottomSheetContent/index.tsx
  src/pages/Post/PostUpload/SearchBottomSheetContent/styles.tsx
  src/pages/Post/PostUpload/ToggleSwitch/styles.tsx
  src/pages/Post/PostUpload/index.tsx
  src/pages/Post/PostUpload/styles.tsx
  src/pages/Post/index.tsx
  src/pages/Post/styles.tsx
Labels: refactor

#126 [OD-172] eslint-plugin-import 적용 테스트
  src/apis/auth/index.ts
  src/apis/core/index.ts
  src/apis/matching/index.ts
  src/apis/post-comment/index.ts
  src/apis/post-like/index.ts
  src/apis/post-report/dto.ts
  src/apis/post-report/index.ts
  src/apis/post/index.ts
  src/apis/user-block/index.ts
  src/apis/user-report/index.ts
  src/apis/user/index.ts
  src/components/Icons/Alarm.tsx
  src/components/Icons/Heart.tsx
  src/components/Icons/Home.tsx
  src/components/Icons/Like.tsx
  src/components/Icons/Message.tsx
  src/components/Icons/MyPage.tsx
  src/components/Icons/Photo.tsx
  vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: refactor

#127 [OD-159] 배포 전 전체 점검
  src/apis/chatting/dto.ts
  src/apis/post-comment/dto.ts
  src/apis/post-comment/index.ts
  src/apis/post-like/dto.ts
  src/apis/post-like/index.ts
  src/apis/post-report/dto.ts
  src/apis/post-report/index.ts
  src/apis/post/dto.ts
  src/apis/post/index.ts
  src/components/BottomButton/index.tsx
  src/components/ClothingInfoItem/index.tsx
  src/components/ClothingInfoItem/styles.tsx
  src/components/ConfirmationModal/index.tsx
  src/components/Text/dto.ts
  src/components/TopBar/styles.tsx
  src/pages/Account/AccountCancel/index.tsx
  src/pages/Account/AccountCancel/styles.tsx
  src/pages/Account/AccountEdit/index.tsx
  src/pages/Account/AccountEdit/styles.tsx
  src/pages/Account/AccountSetting/index.tsx
  src/pages/Account/Verification/styles.tsx
  src/pages/Chats/ChatRoomItem/index.tsx
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/index.tsx
  src/pages/NotFound/styles.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/index.tsx
  src/pages/Post/PostBase/LikeCommentBottomSheetContent/styles.tsx
  src/pages/Post/PostBase/index.tsx
  src/pages/Post/PostBase/styles.tsx
  src/pages/Post/PostImageSelect/index.tsx
  src/pages/Post/PostInstaConnect/index.tsx
  src/pages/Post/PostInstaFeedSelect/index.tsx
  src/pages/Post/PostUpload/ImageSwiper/index.tsx
  src/pages/Post/PostUpload/SearchBottomSheetContent/index.tsx
  src/pages/Post/PostUpload/ToggleSwitch/styles.tsx
  src/pages/Post/PostUpload/index.tsx
  src/pages/Post/PostUpload/styles.tsx
  src/pages/Post/index.tsx
  src/pages/Profile/NavbarProfile/index.tsx
  src/pages/Profile/NavbarProfile/styles.tsx
  src/pages/Profile/PostItem/dto.ts
  src/pages/Profile/PostItem/index.tsx
  src/pages/Profile/PostItem/style.tsx
  src/pages/Profile/ProfileEdit/index.tsx
  src/pages/Profile/ProfileEdit/styles.tsx
  src/pages/Profile/UserProfile/dto.ts
  src/pages/Profile/UserProfile/index.tsx
  src/pages/Profile/UserProfile/style.tsx
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
  src/pages/SignUp/TermsAgreement/styles.tsx
  src/styles/GlobalStyles.ts
Labels: fix, feat

#128 [OD-159] 채팅 UI 수정
  src/assets/default/send-message.svg
  src/pages/Chats/ChatRoom/ChatBox/index.tsx
  src/pages/Chats/ChatRoom/ChatBox/styles.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/styles.tsx
Labels: refactor
